"""Build the Fe56 input files ACHILLES v0.3.1 lacks (it ships C12/O16/Ar40 only).

Writes into the ACHILLES checkout's data tree (untracked there):
  data/Spectral_Functions/pke56{p,n}_tot.data   Benhar Fe56 spectral function
  data/info_Fe56_pke.data                       two-line pointer file
  data/densities/rho_Fe_{p,n}.txt               2pF point-nucleon densities
  data/configurations/FE56_configs_2pF.out.gz   5000 sampled 56-nucleon configs

Sources / conventions (verified 2026-08-19):
- SF table: GENIE_INCLXX's evgen/nucl/spectral_functions/pke56_tot.data (Benhar).
  ACHILLES's pke format = GENIE's minus its two min/max header lines; the
  transform (keep line 1, drop lines 2-3) reproduces ACHILLES's shipped C12
  file byte-identically from GENIE's C12 file. ACHILLES self-normalizes the SF
  (SpectralFunction.cc divides by its own integral), so only the shape matters;
  the same table serves p and n, exactly as GENIE's SpectralFunc uses it and
  as ACHILLES ships for C12 (pke12p == pke12n).
- 2pF density: c = 4.106(45) fm, z = 0.519(21) fm — de Vries, de Jager,
  de Vries, ADNDT 36 (1987) Table I p.505, 56Fe 2pF (La76). Charge-density
  parameters used as point-nucleon shape for both p and n (no neutron skin);
  p normalized to Z=26, n to N=30 (4pi int rho r^2 dr).
- Configurations: positions sampled i.i.d. from the same 2pF (P(r) ~ r^2 rho),
  isotropic, CM-subtracted, weight 1. File format per Configuration.cc:
  header "nnucleons nconfigs maxWgt minWgt"; per config 56 lines
  "pid x y z" (pid "1"=proton, else neutron; shipped files use -1), a weight
  line, a blank line. Positions only feed the cascade / local-kF machinery —
  inert for inclusive QE with the cascade off (|q| ~ 0.7 GeV >> kF).

Usage:  pixi run python report/make_achilles_fe56_inputs.py
"""

import gzip
import hashlib
from pathlib import Path

import numpy as np

ACHILLES_DATA = Path("/exp/dune/app/users/liangliu/ACHILLES/Achilles/data")
GENIE_PKE56 = Path("/exp/dune/app/users/liangliu/GENIE/GENIE_INCLXX/Generator"
                   "/data/evgen/nucl/spectral_functions/pke56_tot.data")

C_2PF, Z_2PF = 4.106, 0.519   # fm (de Vries 1987, 56Fe 2pF, La76)
Z_FE, N_FE = 26, 30
N_CONFIGS = 5000
SEED = 20260819


def sha(p):
    return hashlib.sha256(Path(p).read_bytes()).hexdigest()[:16]


def write_sf():
    lines = GENIE_PKE56.read_text().splitlines(keepends=True)
    out = lines[0] + "".join(lines[3:])       # drop GENIE's min/max header lines
    for sp in ("p", "n"):
        f = ACHILLES_DATA / "Spectral_Functions" / f"pke56{sp}_tot.data"
        f.write_text(out)
        print(f"wrote {f}  sha256:{sha(f)}")
    info = ACHILLES_DATA / "info_Fe56_pke.data"
    info.write_text("data/Spectral_Functions/pke56p_tot.data\n"
                    "data/Spectral_Functions/pke56n_tot.data\n")
    print(f"wrote {info}")


def rho_2pf(r):
    return 1.0 / (1.0 + np.exp((r - C_2PF) / Z_2PF))


def write_densities():
    r = np.arange(0.0, 10.0 + 1e-9, 0.02)
    shape = rho_2pf(r)
    norm = np.trapezoid(4 * np.pi * r**2 * shape, r)   # -> multiply to reach Z/N
    for sp, nnuc in (("p", Z_FE), ("n", N_FE)):
        rho = shape * nnuc / norm
        f = ACHILLES_DATA / "densities" / f"rho_Fe_{sp}.txt"
        # Nucleus.cc skips exactly 16 header lines, then reads (r, rho, err).
        hdr = [f"#56Fe_{sp}", "", "#", "",
               "#R = radius in fm",
               f"#RHO = {'proton' if sp == 'p' else 'neutron'} density in 1/fm**3",
               "#DRHO = error (0: analytic 2pF, de Vries 1987 La76 c=4.106 z=0.519)", "",
               "#Normalization",
               f"#4*PI*TOTINT(RHO*R**2:R) = {nnuc}", "",
               "#generated by report/make_achilles_fe56_inputs.py", "",
               "#rms radii", "",
               "#   R      RHO    DRHO"]
        assert len(hdr) == 16
        rows = "\n".join(f"{ri:.6f} {di:.8f}  0.0" for ri, di in zip(r, rho))
        f.write_text("\n".join(hdr) + "\n" + rows + "\n")
        print(f"wrote {f}  (norm check: "
              f"{np.trapezoid(4 * np.pi * r**2 * rho, r):.4f} vs {nnuc})")


def write_configs():
    rng = np.random.default_rng(SEED)
    r = np.arange(0.0, 12.0, 0.005)
    pdf = r**2 * rho_2pf(r)
    cdf = np.cumsum(pdf); cdf /= cdf[-1]
    a = Z_FE + N_FE
    out = [f"{a} {N_CONFIGS} 1.0 1.0"]
    for _ in range(N_CONFIGS):
        rad = np.interp(rng.random(a), cdf, r)
        cth = rng.uniform(-1, 1, a); phi = rng.uniform(0, 2 * np.pi, a)
        sth = np.sqrt(1 - cth**2)
        pos = np.column_stack([rad * sth * np.cos(phi),
                               rad * sth * np.sin(phi), rad * cth])
        pos -= pos.mean(axis=0)                      # CM at origin
        pids = ["1"] * Z_FE + ["-1"] * N_FE
        for pid, (x, y, z) in zip(pids, pos):
            out.append(f"{pid:>4s} {x: .16E} {y: .16E} {z: .16E}")
        out.append("1.0")
        out.append("")
    f = ACHILLES_DATA / "configurations" / "FE56_configs_2pF.out.gz"
    with gzip.open(f, "wt") as fh:
        fh.write("\n".join(out) + "\n")
    print(f"wrote {f}  ({N_CONFIGS} configs, seed {SEED}, sha256:{sha(f)})")


def patch_particles():
    """Register the Fe56 nucleus PID (1000260560) in data/Particles.yml —
    the event writer throws 'Invalid PID' without it. Mass: atomic mass
    55.9349375 u (AME2020) x 931.49410242 MeV/u minus 26 m_e = nuclear mass,
    same convention as the shipped Ar40 entry (37215.8). Idempotent."""
    f = ACHILLES_DATA / "Particles.yml"
    text = f.read_text()
    if "1000260560" in text:
        print(f"{f} already has Fe56")
        return
    mass = 55.9349375 * 931.49410242 - 26 * 0.51099895
    ar_line = "    - Particle: [1000180400, 37215.8, 0.0, 0, 0, 0, 0, 1, 0, true, true, argon, antiargon]"
    fe_line = (f"    - Particle: [1000260560, {mass:.1f}, 0.0, 0, 0, 0, 0, 1, 0, "
               "true, true, iron, antiiron]")
    if ar_line not in text:
        raise RuntimeError("Ar40 anchor line not found in Particles.yml")
    f.write_text(text.replace(ar_line, ar_line + "\n" + fe_line))
    print(f"patched {f}: Fe56 mass {mass:.1f} MeV")


if __name__ == "__main__":
    write_sf()
    write_densities()
    write_configs()
    patch_particles()
