"""PDG resolution for the GENIE adapter — a thin loader of the repo-shared
`shared/pdg.json` (the SAME data genie-agent/lib/pdg.py reads, no cross-import).

Generated by `shared/build_pdg.py` from GENIE's PDG table + the PDG API; nuclei
resolve by formula from the element->Z table. Kept byte-for-byte equivalent to
genie-agent/lib/pdg.py except for the path depth to the shared file.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[3]      # jobsub-agent/adapters/genie/ -> repo root
_PDG_JSON = _REPO_ROOT / "shared" / "pdg.json"

_data = json.loads(_PDG_JSON.read_text())

_PROBES: dict[str, dict] = _data["probes"]
_NUCLEONS: dict[str, dict] = _data["nucleons"]
ELEMENTS: dict[str, int] = _data["elements"]
_Z_TO_SYMBOL: dict[int, str] = {z: s for s, z in ELEMENTS.items()}

ALIAS_TO_PDG: dict[str, int] = {}
_CODE_TO_CANONICAL: dict[int, str] = {}
for _entry in (*_PROBES.values(), *_NUCLEONS.values()):
    _code = _entry["code"]
    _CODE_TO_CANONICAL[_code] = _entry["canonical"]
    for _a in _entry["aliases"]:
        ALIAS_TO_PDG[_a.lower()] = _code

CHARGED_LEPTON_PDGS = frozenset(
    e["code"] for e in _PROBES.values() if e["kind"] == "charged_lepton"
)
NEUTRINO_PDGS = frozenset(
    e["code"] for e in _PROBES.values() if e["kind"] == "neutrino"
)

_NUCLEUS_RE = re.compile(r"^([A-Z][a-z]?)(\d+)$")
_NUCLEUS_CODE_MIN = 1_000_000_000


def _nucleus_code(symbol: str, mass_number: int) -> int:
    return _NUCLEUS_CODE_MIN + ELEMENTS[symbol] * 10_000 + mass_number * 10


def resolve_pdg(value: str | int) -> int:
    if isinstance(value, int):
        return value
    v = str(value).strip()
    if v.lower() in ALIAS_TO_PDG:
        return ALIAS_TO_PDG[v.lower()]
    m = _NUCLEUS_RE.match(v)
    if m and m.group(1) in ELEMENTS:
        return _nucleus_code(m.group(1), int(m.group(2)))
    try:
        return int(v)
    except ValueError:
        known = ", ".join(sorted(ALIAS_TO_PDG))
        raise ValueError(
            f"Unknown PDG alias '{v}'. Known particle aliases: {known}. "
            f"Nuclei use '<Symbol><A>' (e.g. 'Ar40', 'C12')."
        )


def canonical_probe(value: str | int) -> str:
    return _CODE_TO_CANONICAL.get(resolve_pdg(value), str(resolve_pdg(value)))


def canonical_target(value: str | int) -> str:
    code = resolve_pdg(value)
    if code in _CODE_TO_CANONICAL:
        return _CODE_TO_CANONICAL[code]
    if code >= _NUCLEUS_CODE_MIN:
        z = (code // 10_000) % 1_000
        a = (code // 10) % 1_000
        sym = _Z_TO_SYMBOL.get(z)
        if sym:
            return f"{sym}{a}"
    return str(code)
